<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => '2022-03-22 10:29:10',
                'email' => 'superadmin@yopmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 1,
                'is_active' => 1,
                'name' => 'Super Admin',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => '75o1KQTmL9h8vQBaKMwVBgB90QZDfyy4xHc48dAxqmk5HQkWqCP2wa2yPSkX',
                'signature' => NULL,
                'updated_at' => '2022-07-07 15:01:15',
            ),
            1 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => '2022-03-22 10:29:10',
                'email' => 'admin@yopmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 2,
                'is_active' => 1,
                'name' => 'Admin',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-03-23 07:19:13',
            ),
            2 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'shahril.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 11,
                'is_active' => 1,
                'name' => 'Shahrilnizam Bin Mohamad',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:32:10',
            ),
            3 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'suandy.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 12,
                'is_active' => 1,
                'name' => 'Suandy Bin Samsudin',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:33:18',
            ),
            4 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'shalilatharash.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 13,
                'is_active' => 1,
                'name' => 'Shalilatharash Bin Jalil',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:35:52',
            ),
            5 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'haryati.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 14,
                'is_active' => 1,
                'name' => 'Haryati Binti Moktar',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:35:40',
            ),
            6 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'adli.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 15,
                'is_active' => 1,
                'name' => 'Adli Ikhwan Bin Yusri',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:35:30',
            ),
            7 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'kussairi.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 16,
                'is_active' => 1,
                'name' => 'Ahmad Kussairi Bin Sutikno',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:46:10',
            ),
            8 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'huraidi.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 17,
                'is_active' => 1,
                'name' => 'Huraidi Haidar Bin Adnan',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:45:56',
            ),
            9 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'syafiqazwan.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 18,
                'is_active' => 1,
                'name' => 'Mohamad Syafiq Azwan Bin Mustafa',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:47:47',
            ),
            10 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'anasamzary.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 19,
                'is_active' => 1,
                'name' => 'Anas Amzary Bin Othman',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:48:00',
            ),
            11 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'hayatulfarah.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 20,
                'is_active' => 1,
                'name' => 'Nur Hayatulfarah Binti Roslan',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:48:14',
            ),
            12 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'nisa.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 21,
                'is_active' => 1,
                'name' => 'Nurhanisah Binti Ismail',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:48:31',
            ),
            13 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'hakime.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 22,
                'is_active' => 1,
                'name' => 'Mohd Hakime Bin Md Nasri',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:49:03',
            ),
            14 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'saigowthamjuttiga@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 23,
                'is_active' => 1,
                'name' => 'Saigowtham Juttiga',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:49:19',
            ),
            15 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'arinaadlina.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 24,
                'is_active' => 0,
                'name' => 'Nur Arina Adlina Binti Muhamad Saladin',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-13 19:27:41',
            ),
            16 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'husnina.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 25,
                'is_active' => 1,
                'name' => 'Nur Husnina Binti Mat Azlan',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:49:32',
            ),
            17 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'hafiz.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 26,
                'is_active' => 1,
                'name' => 'Muhammad Hafiz Ruslan',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:49:46',
            ),
            18 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'mutaqim.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 27,
                'is_active' => 1,
                'name' => 'Mutaqim Abdul Hamid',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 12:50:10',
            ),
            19 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'azuharaziz.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 28,
                'is_active' => 1,
                'name' => 'Muhamad Azuhar Aziz Bin Sukri',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 14:14:27',
            ),
            20 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'akmal00.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 29,
                'is_active' => 1,
                'name' => 'Muhammad Akmal Shahrin Bin Mazni',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 14:14:46',
            ),
            21 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'muhddzikrullah.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 30,
                'is_active' => 1,
                'name' => 'Muhd. Dzikrullah Bin Kalana',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 14:15:08',
            ),
            22 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'indera.unijaya@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 31,
                'is_active' => 1,
                'name' => 'Indera Izzwan Bin Mohd Fuad',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-14 14:15:26',
            ),
            23 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => '2022-07-07 21:26:29',
                'email' => 'shatirah',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 32,
                'is_active' => 1,
                'name' => 'Shatirah',
                'no_ic' => NULL,
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-07-07 21:26:29',
            ),
            24 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'pl1@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 33,
                'is_active' => 1,
                'name' => 'Test Pengguna Luar 1',
                'no_ic' => '123123123123',
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-09-27 18:32:44',
            ),
            25 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'pl2@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 35,
                'is_active' => 1,
                'name' => 'Test Pengguna Luar 2',
                'no_ic' => '213213123123',
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-09-27 18:34:41',
            ),
            26 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => NULL,
                'email' => 'admintest@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 36,
                'is_active' => 1,
                'name' => 'Admin',
                'no_ic' => '453534534534',
                'password' => '$2a$12$CXzdGmTGiGF.7NURatRG1OKd/4gRKxUSZT1NwEW8i3xx4crVSpdnC',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2022-09-27 18:35:08',
            ),
            27 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => '2023-05-23 14:58:35',
                'email' => 'hv@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 37,
                'is_active' => 1,
                'name' => 'Helpdesk Vendor',
                'no_ic' => '123456789012',
                'password' => '$2y$10$kFJISMkBXupwJYytZ7rR4OCwFvIHaKrnMS9OolTFuexrefJC3FRJS',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2023-05-23 15:01:15',
            ),
            28 => 
            array (
                'avatar' => NULL,
                'avatar_original' => NULL,
                'created_at' => '2023-05-23 14:59:35',
                'email' => 'hp_btm@gmail.com',
                'email_verified_at' => NULL,
                'google_id' => NULL,
                'id' => 38,
                'is_active' => 1,
                'name' => 'Pegawai BTM',
                'no_ic' => '123456789012',
                'password' => '$2y$10$IWYoq7kpindG91bWFotNFO7HOhwcdlmXLyvGEJshUUYtwpcUmjPxy',
                'remember_token' => NULL,
                'signature' => NULL,
                'updated_at' => '2023-05-23 15:00:31',
            ),
        ));
        
        
    }
}